---
- name: install isc-dhcp-server
  apt:
    name: isc-dhcp-server
    state: present

- name: configure isc-dhcp-server interface
  template:
    src: isc-dhcp-server
    dest: /etc/default/
  notify: restart dhcp

- name: configure dhcpd.conf
  template:
    src: dhcpd.conf
    dest: /etc/dhcp/
  notify: restart dhcp